GameStore/Controllers/CartController.cs
using GameStore.BLL.Interfaces;
using GameStore.BLL.Models;
using GameStore.DAL.Entities;
using GameStore.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace GameStore.Controllers
{
    public class CartController : Controller
    {
        private readonly IGameService _gameService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public CartController(UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            RoleManager<IdentityRole> roleManager, IGameService gameService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _gameService = gameService;
        }

        public IActionResult Index()
        {
            var cart = GetCartFromSession();

            return View(cart);
        }

        public IActionResult Buy(Guid id)
        {
            var userId = _userManager.GetUserId(HttpContext.User);

            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var game = _gameService.GetById(id);

            var cart = HttpContext.Session.Get<List<CartModel>>("cart");

            if (cart == null)
            {
                cart = new List<CartModel>
                {
                      new CartModel { Game = game, Quantity = 1 }
                };

            }
            else
            {
                int index = cart.FindIndex(w => w.Game.Id == id);

                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new CartModel { Game = game, Quantity = 1 });
                }
            }

            HttpContext.Session.Set<List<CartModel>>("cart", cart);

            return RedirectToAction("Index");
        }
        public IActionResult Remove(Guid id)
        {

            var cart = HttpContext.Session.Get<List<CartModel>>("cart");

            int index = cart.FindIndex(w => w.Game.Id == id);

            cart.RemoveAt(index);

            HttpContext.Session.Set<List<CartModel>>("cart", cart);

            return RedirectToAction("Index");
        }

        public IActionResult Add(Guid id)
        {
            var cart = HttpContext.Session.Get<List<CartModel>>("cart");

            int index = cart.FindIndex(w => w.Game.Id == id);

            cart[index].Quantity++;

            HttpContext.Session.Set<List<CartModel>>("cart", cart);

            return RedirectToAction("Index");
        }

        public IActionResult Minus(Guid id)
        {
            // TODO: 1, 2, 3

            // 1) if you return the List please name variables in the plural, since the slightly ambiguous "cart"

            // 2) it seems not entirely logical to create a new CardModel for each game
            // instead you could create one CardModel with Dictionary<GameModel, int> to locate here Quantity
            // and game or even just Dictionary<Guid, int> for GameId and Quantity not to overload session memory

            // 3) try to use LINQ expressions and simplify this logic 
            // for instance:
            // var cart = carts.FirstOrDefault(x => x.Game.Id == id);
            // if (cart is null) return View("Index");
            //
            // if (cart.Quantity == 1)
            //   cart.Remove(t);
            // else
            //   cart.Quantity--;
            // but consider the second point in this case

            var cart = HttpContext.Session.Get<List<CartModel>>("cart");

            int index = cart.FindIndex(w => w.Game.Id == id);

            if (cart[index].Quantity == 1)
            {
                cart.RemoveAt(index);
            }
            else
            {
                cart[index].Quantity--;
            }

            HttpContext.Session.Set<List<CartModel>>("cart", cart);

            return RedirectToAction("Index");
        }

        public IActionResult Order()
        {
            var cart = GetCartFromSession();

            return View(cart);
        }

        public List<CartModel> GetCartFromSession()
        {
            var cart = HttpContext.Session.Get<List<CartModel>>("cart");

            if (cart != null)
            {
                ViewBag.total = cart.Sum(s => s.Quantity * s.Game.Price);
                ViewBag.count = cart.Count();
            }
            else
            {
                cart = new List<CartModel>();
                ViewBag.total = 0;
                ViewBag.count = 0;
            }

            return cart;
        }
    }
}

GameStore/Controllers/CommentController.cs
using GameStore.BLL.Interfaces;
using GameStore.BLL.Models;
using GameStore.DAL.Entities;
using GameStore.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Storage;
namespace GameStore.Controllers
{
    public class CommentController : Controller
    {
        private readonly IGameService _gameService;
        private readonly IGenreService _genreService;
        private readonly ICommentService _commentService;
        private readonly UserManager<ApplicationUser> _userManager;
        public CommentController(IGameService gameService,
            IGenreService genreService,
            ICommentService commentService,
            UserManager<ApplicationUser> userManager)
        {
            _gameService = gameService;
            _genreService = genreService;
            _commentService = commentService;
            _userManager = userManager;
        }

        public IActionResult DeleteComment(Guid id)
        {
            var comment = _commentService.GetById(id);

            return PartialView("_DeleteCommentPartialView", comment);
        }

        [HttpPost]
        public IActionResult DeleteComment(CommentModel item)
        {
            item.UserId = _userManager.GetUserAsync(User).Result.Id;

            item.IsDeleted=true;

            ModelState.ClearValidationState(nameof(CommentModel));

            if (!TryValidateModel(item, nameof(CommentModel)))
            {
                _commentService.Update(item);

                return RedirectToAction("Details", "Game", new { id = item.GameId });
            }
            return View("Index", "Home");
        }
        
        public IActionResult EditComment(Guid id)
        {
            var comment = _commentService.GetById(id);

            return PartialView("_EditCommentPartialView", comment);
        }

        [HttpPost]
        public IActionResult EditComment(CommentModel item)
        {
            item.UserId = _userManager.GetUserAsync(User).Result.Id;

            ModelState.ClearValidationState(nameof(CommentModel));

            if (!TryValidateModel(item, nameof(CommentModel)))
            {
                _commentService.Update(item);

                TempData["Success"] = "The comment has been updated!";

                return RedirectToAction("Details","Game", new { id = item.GameId });
            }
            return View("Index", "Home");
        }

        public IActionResult RestoreComment(Guid id)
        {
            var comment = _commentService.GetById(id);

            return PartialView("_RestoreCommentPartialView", comment);
        }

        [HttpPost]
        public IActionResult RestoreComment(CommentModel item)
        {
            item.UserId = _userManager.GetUserAsync(User).Result.Id;

            item.IsDeleted = false;

            ModelState.ClearValidationState(nameof(CommentModel));

            if (!TryValidateModel(item, nameof(CommentModel)))
            {
                _commentService.Update(item);

                return RedirectToAction("Details", "Game", new { id = item.GameId });
            }

            return View("Index", "Home");
        }
    }
}

GameStore/Controllers/GameController.cs
using GameStore.BLL.Interfaces;
using GameStore.BLL.Models;
using GameStore.DAL.Entities;
using GameStore.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Text;
using System;
using System.Data.Common;

namespace GameStore.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameService _gameService;
        private readonly IGenreService _genreService;
        private readonly ICommentService _commentService;
        private readonly IGameGenreService _gameGenreService;
        private readonly UserManager<ApplicationUser> _userManager;
        public GameController(IGameService gameService,
            IGenreService genreService,
            ICommentService commentService,
            IGameGenreService gameGenreService,
            UserManager<ApplicationUser> userManager)
        {
            _gameService = gameService;
            _genreService = genreService;
            _commentService = commentService;
            _gameGenreService = gameGenreService;
            _userManager = userManager;
        }

        //Get: Game/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            GameViewModel genres = new GameViewModel(_genreService);

            ViewBag.Genres = genres.genreList;

            return View();
        }

        // POST: Game/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(GameModel item)
        {
            //Create Guid
            item.Id = Guid.NewGuid();

            //Select Genres
            GameViewModel genres = new GameViewModel(_genreService);

            ViewBag.Genres = genres.genreList;

            string[] gameGenres = Request.Form["listGenres"].ToString().Split(",");

            List<GameGenreModel> gameGenreModel = new List<GameGenreModel>();

            foreach (string id in gameGenres)
            {
                gameGenreModel.Add(new GameGenreModel
                {
                    Id = Guid.NewGuid(),
                    GameId = item.Id,
                    GenreId = new Guid(id)
                });
            }
            item.GameGenres = gameGenreModel;

            //Upload Image
            var contextForm = Request.Form.Files;
            if (contextForm != null && contextForm.Count > 0)
            {
                var formFile = contextForm[0];

                if (formFile.Length > 0)
                {
                    using (var inputStream = new MemoryStream())
                    {
                        formFile.CopyTo(inputStream);
                        item.PhotoFileName = formFile.FileName;
                        item.Photo = inputStream.ToArray();
                    }
                }
            }
            else
            {
                var fileStream = System.IO.File.Open("wwwroot/img/no-image.png",FileMode.Open);

                var memoryStream = new MemoryStream();

                fileStream.CopyTo(memoryStream);

                item.Photo = memoryStream.ToArray();
                item.PhotoFileName = fileStream.Name;
            }

            ModelState.ClearValidationState(nameof(GameModel));
            if (!TryValidateModel(item, nameof(GameModel)))
            {
                _gameService.Add(item);
                TempData["Success"] = "The game has been created!";
                return RedirectToAction("Index", "Home");
            }
            return View(item);
        }

        // Get: Game/Details/Id
        public IActionResult Details(Guid id)
        {
            var game = _gameService.GetById(id);

            CommentViewModel result = new CommentViewModel();

            result.Game = game;
            result.Comments = _commentService.GetAllByGameId(id).ToList();

            return View(result);
        }

        // Post: Game/Details/Id
        [HttpPost]
        public IActionResult Details(CommentViewModel commentViewModel)
        {
            var userId = _userManager.GetUserId(HttpContext.User);

            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }

            CommentModel model = new CommentModel();
            model.Id = Guid.NewGuid();
            model.GameId = commentViewModel.GameId;
            model.UserId = _userManager.GetUserAsync(User).Result.Id;
            model.CommentText = commentViewModel.CommentText;
            model.CommentDate = DateTime.Now;

            if (commentViewModel.PostType == "reply")
            {
                model.ParentId = commentViewModel.ParentId;
            }

            _commentService.Add(model);

            return RedirectToAction("Details", new { id = commentViewModel.GameId }); 
        }

        // GET /Game/Edit/Id
        public IActionResult Edit(Guid id)
        {
            GameViewModel genres = new GameViewModel(_genreService);
            ViewBag.Genres = genres.genreList;

            var item = _gameService.GetById(id);
            genres.Id = item.Id;
            genres.Name = item.Name;
            genres.Description = item.Description;
            genres.Price = item.Price;
            genres.GameGenres = item.GameGenres;
            genres.Photo = item.Photo;
            genres.PhotoFileName = item.PhotoFileName;

            if (genres == null)
            {
                return NotFound();
            }

            return View(genres);
        }

        // POST: Game/Edit/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(GameModel item)
        {
            
            var contextForm = Request.Form.Files;

            if (contextForm != null && contextForm.Count > 0)
            {
                var formFile = contextForm[0];

                if (formFile.Length > 0)
                {
                    using (var inputStream = new MemoryStream())
                    {
                        formFile.CopyTo(inputStream);
                        item.PhotoFileName = formFile.FileName;
                        item.Photo = inputStream.ToArray();
                    }
                }
            }
            else
            {
                var fileStream = System.IO.File.Open("wwwroot/img/no-image.png", FileMode.Open);

                var memoryStream = new MemoryStream();

                fileStream.CopyTo(memoryStream);

                item.Photo = memoryStream.ToArray();
                item.PhotoFileName = fileStream.Name;
            }

            //Remove Genres related to the Game
            var gameGenresList = _gameGenreService.GetAll().Where(x => x.GameId == item.Id);

            foreach (var gameGenre in gameGenresList)
            {
                _gameGenreService.Delete(gameGenre.GameId, gameGenre.GenreId);
            }


            //Assign Genres to the Game
            string[] gameGenres = Request.Form["listGenres"].ToString().Split(",");

            foreach (string id in gameGenres)
            {
                var temp = new GameGenreModel
                {
                    Id = Guid.NewGuid(),
                    GameId = item.Id,
                    GenreId = new Guid(id)
                };
                _gameGenreService.Add(temp);
            }

            //Check model and save in the Database
            ModelState.ClearValidationState(nameof(GameModel));

            if (!TryValidateModel(item, nameof(GameModel)))
            {
                _gameService.Update(item);
                TempData["Success"] = "The game has been updated!";
                return RedirectToAction("Index", "Home");
            }
            
            return View(item);
        }

        // GET /Game/Delete/ID
        public IActionResult Delete(Guid id)
        {
            var item = _gameService.GetById(id);

            if (item == null)
            {
                TempData["Error"] = "The game does not exist!";
            }
            else
            {
                _gameService.Delete(item.Id);
                TempData["Success"] = "The game has been deleted!";
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

GameStore/Views/Game/Details.cshtml
@model GameStore.ViewModel.CommentViewModel
@using GameStore.DAL.Entities
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Details";
    TempData["ReloadPage"] = true;
}
@{
    var base64 = Convert.ToBase64String(@Model.Game.Photo);
    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
}
<!-- Page info section -->
<section class="page-info-section set-bg" data-setbg="@imgSrc">
    <div class="pi-content">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-6 text-white">
                    <h2>@Model.Game.Name</h2>
                    <p>@Model.Game.Description</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Page info section -->
<!-- Page section -->
<section class="page-section single-blog-page spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                <div class="blog-thumb set-bg" data-setbg="@imgSrc">
                </div>
                <div class="blog-content">
                    @foreach (var assignedGame in Model.Game.GameGenres)
                    {
                        <div class="container">
                            <div class="row">
                                <div class="col-md">
                                   <h4>@assignedGame.Genre.Name</h4> 
                                </div>
                            </div>
                        </div>
                    }
                    <h3>@Model.Game.Name</h3>
                    <p>@Model.Game.Description</p>
                    
                    @if (ViewContext.HttpContext.User.IsInRole("Administrator"))
		            {
                    <div>
					<a asp-controller="Game" asp-action="Edit" asp-route-id="@Model.Game.Id"><input type="button" class="btn btn-warning" value="Edit Game" /></a>
                            <a asp-controller="Game" asp-action="Delete" asp-route-id="@Model.Game.Id"><input type="button" class="btn btn-danger" value="Delete Game" /></a>
                    
				    </div>
                    }
                    else
                    {
                        <a asp-controller="Cart" asp-action="Buy" asp-route-id="@Model.Game.Id"><input type="button" class="btn btn-success" value="Buy $@Model.Game.Price" /></a>
                    }

                </div>
                <!--Comment section-->
                <div class="comment-warp">
                    <h4 class="comment-title">Comments</h4>
                    <ul class="comment-list">

                        @foreach (var comments in Model.Comments.Where(x => x.ParentId == null))
                        {
                            <li>
                                <div class="comment">
                                    @if (comments.User.ProfilePicture != null)
                                    {
                                        <div class="comment-avator set-bg" data-setbg="data:image/*;base64,@(Convert.ToBase64String(comments.User.ProfilePicture))"></div>
                                    }
                                    <div class="comment-content">
                                        <h5>@comments.User.FirstName @comments.User.LastName<span>@comments.CommentDate</span></h5>
                                        @if (comments.IsDeleted)
                                        {
                                            <p>Deleted</p>
                                        }
                                        else
                                        {
                                            <p>@comments.CommentText</p>
                                            @if (comments.UserId != UserManager.GetUserAsync(User).Result.Id)
                                            {
                                                <a href="" id="@comments.Id" class="reply">Reply</a>
                                            }
                                        }

                                        @if (comments.UserId == UserManager.GetUserAsync(User).Result.Id && !comments.IsDeleted)
                                        {
                                            <a asp-controller="Comment" asp-action="EditComment" asp-route-id="@comments.Id" class="reply" data-toggle="modal" data-target="@("#EditComment-"+comments.Id)">Edit</a>
                                            @await Html.PartialAsync("_EditCommentPartialView", comments)
                                            <a asp-controller="Comment" asp-action="DeleteComment" asp-route-id="@comments.Id" class="reply" data-toggle="modal" data-target="@("#DeleteComment-"+comments.Id)">Delete</a>
                                            @await Html.PartialAsync("_DeleteCommentPartialView", comments)


                                        }
                                        else if (comments.UserId == UserManager.GetUserAsync(User).Result.Id)
                                        {
                                            <a asp-controller="Comment" asp-action="RestoreComment" asp-route-id="@comments.Id" class="reply" data-toggle="modal" data-target="@("#RestoreComment-"+comments.Id)">Restore</a>
                                            @await Html.PartialAsync("_RestoreCommentPartialView", comments)
                                        }
                                        <!-- For-->
                                        @foreach (var replies in comments.Children)
                                        {
                                            <div class="comment-reply">
                                                <div class="comment">
                                                    @if (replies.User.ProfilePicture != null)
                                                    {
                                                        <div class="comment-avator set-bg" data-setbg="data:image/*;base64,@(Convert.ToBase64String(replies.User.ProfilePicture))"></div>
                                                    }
                                                    <div class="comment-content">
                                                        <h5>@replies.User.FirstName @replies.User.LastName<span>@replies.CommentDate</span></h5>
                                                        @if (replies.IsDeleted)
                                                        {
                                                            <p>Deleted</p>
                                                        }
                                                        else
                                                        {
                                                            <p>@replies.CommentText</p>
                                                            @if (replies.UserId != UserManager.GetUserAsync(User).Result.Id)
                                            {
                                                <a href="" id="@replies.Id" class="reply">Reply</a>
                                            }
                                                        }



                                                        @if (replies.UserId == UserManager.GetUserAsync(User).Result.Id && !replies.IsDeleted)
                                                        {
                                                            <a asp-controller="Comment" asp-action="EditComment" asp-route-id="@replies.Id" class="reply" data-toggle="modal" data-target="@("#EditComment-"+replies.Id)">Edit</a>
                                                            @await Html.PartialAsync("_EditCommentPartialView", replies)
                                                            <a asp-controller="Comment" asp-action="DeleteComment" asp-route-id="@replies.Id" class="reply" data-toggle="modal" data-target="@("#DeleteComment-"+replies.Id)">Delete</a>
                                                            @await Html.PartialAsync("_DeleteCommentPartialView", replies)
                                                        }
                                                        else if (replies.UserId == UserManager.GetUserAsync(User).Result.Id)
                                                        {
                                                            <a asp-controller="Comment" asp-action="RestoreComment" asp-route-id="@replies.Id" class="reply" data-toggle="modal" data-target="@("#RestoreComment-"+replies.Id)">Restore</a>
                                                            @await Html.PartialAsync("_RestoreCommentPartialView", replies)
                                                        }
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                        <!-- For End Section-->
                                    </div>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
                <div class="comment-form-warp">
                    <h4 class="comment-title">Leave Your Comment</h4>
                    <form method="post" asp-action="Details" asp-controller="Game" enctype="multipart/form-data">
                        <input type="hidden" name="GameId" value="@Model.Game.Id" />
                        <div class="row">
                            <div class="col-lg-12">
                                <textarea type="text" name="CommentText" maxlength="600" placeholder="Leave Comment ..."
                                          style="width:100%; height:60px;"></textarea>
                                <input type="submit" value="Send" class="site-btn btn-sm" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    @*//Get all comment elements*@
        const comments = document.querySelectorAll('.comment');

    @*//Add listeners to all reply buttons*@
        comments.forEach(comment => {
            const replyButton = comment.querySelector('.reply');

            replyButton.addEventListener('click', (event) => {

                event.preventDefault();

                const allReplySections = document.querySelectorAll('.comment-reply-form');

                allReplySections.forEach(replySection => {
                    if (replySection !== replyForm) {
                        replySection.style.display = 'none';
                    }
                });

    @*//Hide the reply button  *@
                    replyButton.style.display = 'none';

                const replyForm = document.createElement('div');
                replyForm.classList.add('comment-reply-form');

                const formHtml = `
            <form method="post" id="reply-form" enctype="multipart/form-data">

            <div class="row">
                <div class="col-md-12">
                        <input type="hidden" name="GameId" value="@Model.Game.Id" />
                        <input type="hidden" name="PostType" value="reply" />

                <textarea name="CommentText" maxlength="600" placeholder="Your Reply"></textarea>
                </div>
                <div class="col-md-12">
                <button type="submit" class="submit-button site-btn btn-sm ">Send</button>
                <button type="button" class="cancel-reply site-btn btn-sm">Cancel</button>
                </div>
            </div>
            </form>
            `;

                replyForm.innerHTML = formHtml;

                comment.appendChild(replyForm);

                const cancelButton = replyForm.querySelector('.cancel-reply');
                cancelButton.addEventListener('click', (event) => {
                    event.preventDefault();
                    replyButton.style.display = 'inline-block';
                    replyForm.remove();
                });

                const replyFormElement = replyForm.querySelector('#reply-form');
                replyFormElement.addEventListener('submit', (event) => {
                    event.preventDefault();

                    const formData = new FormData(replyFormElement);
                    formData.append('ParentId', replyButton.id);
                    console.log(replyButton.id);

                    fetch('/Game/Details', { method: 'post', body: formData })
                        .then(response => {
                            console.log(response);
                            window.location.reload();

                        })
                        .catch(error => {
                            console.log(error);

                        });


                })
            });

    @*Check the nesting level*@
            const nestingLevel = comment.querySelectorAll('.comment-reply').length;

            if (nestingLevel >= 3) {
                replyButton.style.display = 'none';
            }

        });
</script>

GameStore/Views/Game/_DeleteCommentPartialView.cshtml
@model GameStore.BLL.Models.CommentModel
 <div class="modal fade" id="DeleteComment-@Model.Id" aria-labelledby="deleteCommentLabel" aria-hidden="true">
     <div class="modal-dialog">
         <div class="modal-content">
             <div class="modal-header">
                 <h5 class="modal-title" id="deleteCommentLabel">Delete Comment</h5>
                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                     <span aria-hidden="true">&times;</span>
                 </button>
             </div>
             <div class="modal-body">
                <form asp-controller="Comment" asp-action="DeleteComment" method="post">
                     <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                     <div class="form-group">
                        <input type="hidden" asp-for="GameId" value="@Model.GameId" />
                        <input type="hidden" asp-for="Id" value="@Model.Id" />
                        <input type="hidden" asp-for="ParentId" value="@Model.ParentId" />
                        <input type="hidden" asp-for="CommentDate" value="@Model.CommentDate" />
                        <textarea type="text" asp-for="CommentText" maxlength="600"
                                  style="width:100%; height:60px;"></textarea>
                     </div>
                     <div class="modal-footer">
                         <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                         <button type="submit" class="btn btn-primary">Yes</button>
                     </div>
                 </form>
             </div>
         </div>
     </div>
</div>